[package]
name = "numa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotpy = "0.3.5"
russell_lab = "0.4.1"
regex = "1"